### ISSUE TITLE
>> michel pull

### ISSUE THREAD

**Issue by ghost** [chmduquesne/michel#1]
> > michel pull
> > ...
> > TODO LIST LINES
> > ...

Traceback (most recent call last):
  File "/usr/bin/michel", line 9, in <module>
    load_entry_point('michel==0.0.6', 'console_scripts', 'michel')()
  File "/usr/lib/python2.7/site-packages/michel/michel.py", line 90, in main
    print_todolist()
  File "/usr/lib/python2.7/site-packages/michel/michel.py", line 50, in print_todolist
    level = levels[parent_id] + 1
KeyError: u'MDU2MjUzNjE5ODc3ODEyOTM0MjI6MDoxNDI'

**Comment by chmduquesne** [comment]
Ok, so it seems like I can make no assumption upon the order in which I receive the tasks. Basically, it would mean the parent of a task is not yet processed when the subtask is received. I'll try to fix that, but don't count on it right away, I am under heavy workload ATM.

**Comment by ghost** [comment]
The error stop showing!
*
*
Everything looks fine.

Thanks
